name: Sonar
on:
  workflow_run:
    workflows:
    - Tests
    types:
    - completed

jobs:
  analysis:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: github.event.workflow_run.referenced_workflows[0].ref
    - uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: '${{ github.event.workflow_run.referenced_workflows[0].sha }}-app-coverage'
    - name: dummy analysis
      run: |
        ls -la
