name: Tests
on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.event.actor.login }}
    - run: echo ${{ github.event.pull_request.sender.login }}
